version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  commit-message:
      # Prefix all commit messages with "npm"
      prefix: "fix:"
      prefix-development: "ci:"
- package-ecosystem: "docker"
  directory: "/DetectiCam/"
  schedule:
    interval: "daily"
    time: "02:00"
  open-pull-requests-limit: 10
  commit-message:
      # Prefix all commit messages with "npm"
      prefix: "fix:"
      prefix-development: "ci:"
