version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  # ignore:
  #     # Ignore .NET 7 related version
  #     - dependency-name: "Microsoft.Extensions.*"
  #       versions: ["7.x"]
  #     - dependency-name: "Microsoft.NetCore.*"
  #       versions: ["7.x"]
  commit-message:
      # Prefix all commit messages with "npm"
      prefix: "fix"
      prefix-development: "ci"
- package-ecosystem: "docker"
  directory: "/DetectiCam/"
  schedule:
    interval: "daily"
    time: "02:00"
  open-pull-requests-limit: 10
  commit-message:
      # Prefix all commit messages with "npm"
      prefix: "fix"
      prefix-development: "ci"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
      interval: "daily"
  open-pull-requests-limit: 10
  commit-message:
      # Prefix all commit messages with "npm"
      prefix: "fix"
      prefix-development: "ci"
