language: csharp
mono: none
dotnet: 3.1

install:
  - dotnet tool install --global dotnet-sonarscanner --version 4.8.0

solution: DetectiCam.sln
script:
  - dotnet restore
  - dotnet-sonarscanner begin /o:"raimondb" /k:"RaimondB_Detecticam"  /d:sonar.login="$(SONAR_TOKEN)" /d:sonar.host.url="https://sonarcloud.io"
  - dotnet test
  - dotnet-sonarscanner end
  