trigger:
- master

pr:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build & QA
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          dotnet restore
          dotnet tool restore
          #dotnet tool run dotnet-sonarscanner begin /o:"raimondb" /k:"RaimondB_Detecticam"  /d:sonar.login="$(SONAR_TOKEN)" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.branch.name="$(Build.SourceBranch)"
          #dotnet test
          #dotnet tool run dotnet-sonarscanner end /d:sonar.login="$(SONAR_TOKEN)"
          # need to update to java 11 for sonar
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker-compose -f DetectiCam/docker-compose.test.yml run sut
- stage: Release
  displayName: Release a new image on Dockerhub
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          export GH_TOKEN=$(GH_TOKEN)
          echo "token:$GH_TOKEN"
          #echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          #nvm install v12.0.0
          #docker build -f DetectiCam/Dockerfile . -t raimondb/detect-i-cam
          #npm install -g npm
          #npm install
          npx semantic-release
      env:
        GH_TOKEN: $(GH_TOKEN)
