trigger:
- master

pr:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build & QA
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: JavaToolInstaller@0 
      inputs: # make sure Java 11 is installed and pointed to by JAVA_HOME, since the Sonar Scanner requires this to run
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Bash@3
      displayName: Build & Code Analysis
      inputs:
        targetType: 'inline'
        script: |
          dotnet restore
          dotnet tool restore
          dotnet tool run dotnet-sonarscanner begin /o:"raimondb" /k:"RaimondB_Detecticam"  /d:sonar.login="$(SONAR_TOKEN)" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.branch.name="$(Build.SourceBranchName)"
          dotnet test
          dotnet tool run dotnet-sonarscanner end /d:sonar.login="$(SONAR_TOKEN)"
      env:
        SONAR_TOKEN: $(SONAR_TOKEN)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker-compose -f DetectiCam/docker-compose.test.yml run sut
      env:
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)
- stage: Release
  displayName: Release a new image on Dockerhub
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -f DetectiCam/Dockerfile . -t raimondb/detect-i-cam
          npx semantic-release
      env:
        GH_TOKEN: $(GH_TOKEN)
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)