---
version: "2.2"
services:
  detecticam:
    image: raimondb/detect-i-cam:1.0
    container_name: detect-i-cam
    volumes:
      - ./capture:/captures # location to write annotated captured frames to
      - ./config:/config    # directory to load appsettings.json configuration file from
    restart: unless-stopped
