# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Docker Release

on:
    workflow_run:
        workflows: ['.NET Build & Test']                     # runs after CI workflow
        types:
        - completed

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        file: DetectiCam/Dockerfile
        load: true
        tags: raimondb/detect-i-cam
    # - run: docker build -f DetectiCam/Dockerfile . -t raimondb/detect-i-cam
    - uses: actions/setup-node@v3
      with:
# See below for current versions supported by Node-red
# https://nodered.org/docs/faq/node-versions#installing-nodejs
        node-version: 18
        registry-url: https://registry.npmjs.org/
    - run: npm install
    - run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
